name: clean_architecture_kit
description: >-
  A custom linter to enforce Clean Architecture principles in Dart and Flutter projects, with code 
  actions to streamline development.
version: 1.1.0

repository: https://github.com/puntbyte/clean_architecture_kit
homepage: https://github.com/puntbyte/clean_architecture_kit

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ">=0.12.0 <1.0.0"
  code_builder: ^4.10.0
  collection: ^1.19.1
  custom_lint_builder: ">=0.7.0 <1.0.0"
  dart_style: "^3.1.0"
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.26.0
