name: clean_architecture_core
description: >-
  A lightweight companion package for clean_architecture_lints, providing core interfaces like 
  Usecase and Port for building Clean Architecture apps.
version: 1.0.0
repository: https://github.com/puntbyte/clean_architecture_workspace/tree/master/packages/clean_architecture_core
homepage: https://github.com/puntbyte/clean_architecture_workspace/tree/master/packages/clean_architecture_core
issue_tracker: https://github.com/puntbyte/clean_architecture_workspace/issues
topics:
  - clean-architecture
  - architecture
  - clean-architecture-kit

environment:
  sdk: ^3.10.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  fpdart: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
