name: architecture_lints
description: A configuration-driven, architecture-agnostic linter for Dart & Flutter.
version: 1.0.0

topics:
  - lint
  - clean-architecture
  - mvvm

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.0
  code_builder: ^4.10.0
  collection: ^1.19.1
  custom_lint_builder: ^0.8.0
  dart_style: ^3.1.0
  dictionaryx: ^0.3.5
  glob: ^2.1.3
  meta: ^1.17.0
  mustache_template: ^2.0.1
  path: ^1.9.1
  recase: ^4.1.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  pubspec_parse: ^1.5.0
  test: ^1.26.0
