name: example
description: A demonstration project for the clean_architecture_kit package.
version: 2.0.0

publish_to: 'none'

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  bloc: any
  clean_architecture_core:
    path: ../../packages/clean_architecture_core
  flutter_bloc: any

  flutter:
    sdk: flutter

  fpdart: any
  injectable: any

dev_dependencies:
  custom_lint: any

  clean_architecture_lints:
    path: ../../packages/clean_architecture_lints

flutter:
  uses-material-design: true